### ISSUE TITLE
About contributors links

### ISSUE THREAD

**Issue by ahmetcanaydemir** [cagataycali/find-mentor#200]
We are currently redirecting to github links when click on contributor photo. And we also show contributors other than find-mentor users. Clicking on the photo should be redirected to the find-mentor link instead of github link.

![image](https://user-images.githubusercontent.com/8572957/102653693-5dc8eb80-4180-11eb-8b6b-0c1611898506.png)

**Comment by cagataycali** [comment]
We need that feature!

**Comment by mbugrayildiz** [comment]
This is solved and working. We redirect to github only if the person doesn't have a find mentor network profile. Closing the issue.

**Comment by ahmetcanaydemir** [comment]
@mbugrayildiz partly fixed for homepage and how it works page but still persist. Kindly check contributors section on peer pages. https://findmentor.network/peer/ahmet-can-aydemir

**Comment by hasantezcan** [comment]
This bug still continues.  If you try to click my avatar you will redirect to my GitHub account but I did declared my GitHub account on my [`findmentor.network` profile](https://findmentor.network/peer/hasan-tezcan). 

![image](https://user-images.githubusercontent.com/32804505/102782005-a7484f00-43a9-11eb-8179-a794d4cbee70.png)

The problem here: I declared my github link with `www.` subdomain but most of the people declared with out `www`. So we didn't catch thıs error easily.

Now we have to refactor our **fixportocol** function in genrete.js 

https://github.com/cagataycali/find-mentor/blob/cda62a4dc0b42542141f905bb579e808176f1940/generate.js#L54 

with this line  

```js
? 'https://' + url.replace(/https?:\/\/www./gi, '').replace(/\/$/gi, '')
```
After that, we will update the  person.json without `www.`  
 
https://github.com/cagataycali/find-mentor/blob/cda62a4dc0b42542141f905bb579e808176f1940/generate.js#L134-L141

And we can able to control this line exactly.

https://github.com/cagataycali/find-mentor/blob/cda62a4dc0b42542141f905bb579e808176f1940/components/list/ContribList.vue#L2-L9

And we can redirect perfectly in here

:ok_hand:

**Comment by cagataycali** [comment]
`regexp = new RegExp(/https?:\/\/|(www.)/, 'gi')`
